### ISSUE TITLE
OCR_VG关于提升模型的视觉定位能力

### ISSUE THREAD

**Issue by haoranwu22** [LDLINGLINGLING/MiniCPM_Series_Tutorial#1]
我在官方的issues下看到的边界框格式是`<ref>xxx</ref><box>x1 y1 x2 y2</box>`，但是本篇教程用的是`<ref>xxx<box>x1</box><box>y1</box><box>x2</box><box>y2</box></ref>`，请问这会有影响吗？有的话，以哪种格式为主呢？

**Comment by LDLINGLINGLING** [comment]
都可以，因为本来minicpmv并不以定位为主，也就是说预训练这种数据本身就少。
